# Generated by Django 4.2.16 on 2024-09-09 02:55

from django.db import migrations
from django.contrib.auth.models import Group


# WARN This Migration is used to create the user permissions of the project 
# WARN It depencie must be ('users', '0001_initial') - The second migration after the initial one created 


def create_groups(apps, schema_editor):
    GROUPS = ['super', 'admin', 'staff', 'pacient']
    for group in GROUPS:
        Group.objects.get_or_create(name=group)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
