# Generated by Django 4.2.16 on 2024-09-13 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_remove_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='primary_users', to='auth.group'),
        ),
    ]
