# Generated by Django 4.2.16 on 2024-09-11 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_name', models.CharField(blank=True, max_length=150, verbose_name='parent name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=30, region=None, verbose_name='phone number')),
                ('note', models.TextField(blank=True, default='', verbose_name='note')),
                ('country', django_countries.fields.CountryField(default='BR', max_length=2, verbose_name='country')),
                ('city', models.CharField(default='Ilhéus', max_length=180, verbose_name='city')),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='', verbose_name='profile photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
