# Generated by Django 4.2.16 on 2024-09-22 15:05

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(max_length=200, verbose_name='patient name')),
                ('parent_name', models.CharField(max_length=200, verbose_name='parent name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=30, region=None, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('note', models.TextField(blank=True, default='', verbose_name='note')),
                ('country', django_countries.fields.CountryField(default='BR', max_length=2, verbose_name='country')),
                ('city', models.CharField(default='Ilhéus', max_length=180, verbose_name='city')),
                ('profile_photo', models.ImageField(blank=True, default='/profile_default.png', upload_to='', verbose_name='profile photo')),
                ('birth_date', models.DateField()),
                ('expiration_date', models.DateField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
