# Generated by Django 4.2.16 on 2024-10-07 17:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, verbose_name='country'),
        ),
    ]
