# Generated by Django 4.2.16 on 2024-10-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_city_alter_patient_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='phone number'),
        ),
    ]
