# Generated by Django 4.2.16 on 2024-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='parent_name',
            field=models.CharField(max_length=50, verbose_name='parent name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(max_length=50, verbose_name='patient name'),
        ),
    ]
