# Generated by Django 4.2.16 on 2024-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_parent_name_alter_patient_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='parent_name',
            field=models.CharField(max_length=45, verbose_name='parent name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(max_length=45, verbose_name='patient name'),
        ),
    ]
